export const HANDE_APP_MODE = 'HANDE_APP_MODE';
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const SET_CALENDAR_MONTH_STATE = 'SET_CALENDAR_MONTH_STATE';

export const ASYNC_FETCH_USER = 'ASYNC_FETCH_USER';
export const ASYNC_EDIT_USER = 'ASYNC_EDIT_USER';

export const ASYNC_FETCH_GROUPS = 'ASYNC_FETCH_GROUPS';
export const ASYNC_POST_GROUP = 'ASYNC_POST_GROUP';
export const ASYNC_EDIT_GROUP = 'ASYNC_EDIT_GROUP';
export const ASYNC_DELETE_GROUP = 'ASYNC_DELETE_GROUP';
export const ASYNC_REARRANGE_GROUPS = 'ASYNC_REARRANGE_GROUPS';
export const REARRANGE_REDUX_GROUPS = 'REARRANGE_REDUX_GROUPS';

export const ASYNC_FETCH_EVENTS = 'ASYNC_FETCH_EVENTS';
export const ASYNC_POST_EVENT = 'ASYNC_POST_EVENT';
export const ASYNC_EDIT_EVENT = 'ASYNC_EDIT_EVENT';
export const ASYNC_PATCH_EVENT_ISDONE = 'ASYNC_PATCH_EVENT_ISDONE';
export const ASYNC_REARRANGE_EVENTS = 'ASYNC_REARRANGE_EVENTS';
export const REARRANGE_REDUX_EVENTS = 'REARRANGE_REDUX_EVENTS';

export const ASYNC_FETCH_STEPS = 'ASYNC_FETCH_STEPS';
export const ASYNC_POST_STEP = 'ASYNC_POST_STEP';
export const ASYNC_EDIT_STEP = 'ASYNC_EDIT_STEP';
export const ASYNC_PATCH_STEP_ISDONE = 'ASYNC_PATCH_STEP_ISDONE';
export const ASYNC_DELETE_STEP = 'ASYNC_DELETE_STEP';
export const ASYNC_REARRANGE_STEPS = 'ASYNC_REARRANGE_STEPS';
export const REARRANGE_REDUX_STEPS = 'REARRANGE_REDUX_STEPS';
