export const HANDE_APP_MODE = 'HANDE_APP_MODE';
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';

export const ASYNC_FETCH_GROUPS = 'ASYNC_FETCH_GROUPS';
export const ASYNC_POST_GROUP = 'ASYNC_POST_GROUP';
export const ASYNC_EDIT_GROUP = 'ASYNC_EDIT_GROUP';
export const ASYNC_DELETE_GROUP = 'ASYNC_DELETE_GROUP';

export const ASYNC_FETCH_EVENTS = 'ASYNC_FETCH_EVENTS';
export const ASYNC_POST_EVENT = 'ASYNC_POST_EVENT';
export const ASYNC_PATCH_ISDONE = 'ASYNC_PATCH_ISDONE';